name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Show Docker image information
      run: |
        docker images

    - name: Run CI in Docker container
      run: |
        docker run -it malmomani/docker_github_ci_image:tagname /path/to/your/ci/script.sh
