name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Current Directory
      run: |
        ls -l Assessment

    - name: Run Automation Tests
      run: |
        docker run -v $(pwd):/Assessment -w /Assessment malmomani/docker_github_ci_image:tagname mvn test
