name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Automation Tests
      run: |
        docker run --shm-size=2g -v $(pwd)/Assessment:/Assessment -w /Assessment malmomani/docker_github_ci_image:tagname clean compile test

    - name: Get Test Results
      id: test-results
      run: |
        # Extract relevant information from your test execution (example: number of passed/failed tests)
        passed_tests=$(grep -oP 'Passed: \K\d+' Assessment/reports/index.html)
        failed_tests=$(grep -oP 'Failed: \K\d+' Assessment/reports/index.html)
        overall_result=$(grep -oP 'Overall Result: \K\w+' Assessment/reports/index.html)
        
        # Set output variables
        echo "::set-output name=passed_tests::$passed_tests"
        echo "::set-output name=failed_tests::$failed_tests"
        echo "::set-output name=overall_result::$overall_result"

    - name: Post to Discord
      if: always()
      env:
        DISCORD_WEBHOOK_URL: 'https://discord.com/api/webhooks/your_webhook_url'
      run: |
        # Get outputs from previous step
        passed_tests=${{ steps.test-results.outputs.passed_tests }}
        failed_tests=${{ steps.test-results.outputs.failed_tests }}
        overall_result=${{ steps.test-results.outputs.overall_result }}

        # Map colors to the overall result
        case "$overall_result" in
          "Success")
            color="#2ecc71"  # Green
            ;;
          "Failure")
            color="#e74c3c"  # Red
            ;;
          *)
            color="#3498db"  # Blue (default)
            ;;
        esac

        # Post custom message to Discord with colors
        curl -X POST -H 'Content-type: application/json' \
          --data '{"content":"GitHub Actions workflow completed!\n\nTest Results:\nPassed: `'$passed_tests'`\nFailed: `'$failed_tests'`\nOverall Result: `'$overall_result'`","embeds":[{"color":'$color'}]}' \
          $DISCORD_WEBHOOK_URL
