name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Current Directory
      run: |
        ls -l
        ls -l /github/workspace

    - name: Run Automation Tests
      run: |
        docker run -v $(pwd):/github/workspace -w /github/workspace/Assessment malmomani/docker_github_ci_image:tagname mvn -f /github/workspace/Assessment/qa/pom.xml test
