name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Automation Tests
      run: |
        docker run -v $(pwd):/app -w /app malmomani/docker_github_ci_image:tagname npm test
