name: Run Automation Tests

on:
  push:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Automation Tests
      run: |
        docker run --shm-size=2g -v $(pwd)/Assessment:/Assessment -w /Assessment malmomani/docker_github_ci_image:tagname clean compile test

    - name: Post to Discord
      if: always()
      run: |
        DISCORD_WEBHOOK_URL='https://discord.com/api/webhooks/1212835628358570054/qsqoSYcLhb7iws4kwKKVPc-XtG-b5AbmgdSdJEhNwtUOZp6Zg4dw6J2uXPLO7VLpd5kX'
        echo "Discord Webhook URL: $DISCORD_WEBHOOK_URL"
        # Provide a link to download the artifact
        curl -v -X POST -H 'Content-type: application/json' \
          --data '{"content":"GitHub Actions workflow completed!","embeds":[{"title":"HTML Report","description":"[Download HTML Report](https://github.com/'"$GITHUB_REPOSITORY"'/actions/artifacts/'"$GITHUB_RUN_ID"'?workflow=Run+Automation+Tests)"}]}' \
          $DISCORD_WEBHOOK_URL
